server:
  port: 10000
# 配置swagger文档的访问路径
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    url: jdbc:mysql://47.93.46.101:3306/webdav?serverTimezone=Asia/Shanghai&useSSL=FALSE
    username: zhaoyu
    password: zhaoyu123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
webdav:
  username: zhaoyu
  password: 123456
  url: http://47.93.46.101:5244/dav/webdav/
